/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package CRUD;

import CONEXAO_BANCO.Banco_dados;
import java.awt.Component;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextField;

/**
 *
 * @author sog7jvl
 */
public class Tela_pagamento extends javax.swing.JDialog {

    /**
     * Creates new form Tela_pagamento
     */
    public Tela_pagamento(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        idVenda();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTNotaFiscal = new javax.swing.JTextField();
        jTDesconto = new javax.swing.JTextField();
        jTPagamento = new javax.swing.JTextField();
        jLSoma = new javax.swing.JLabel();
        jComboBoxFormaPagamento = new javax.swing.JComboBox<>();
        jLTotalDesconto = new javax.swing.JLabel();
        jLTroco = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Bosch Sans Black", 2, 48)); // NOI18N
        jLabel1.setText("PAGAMENTO:");

        jLabel2.setFont(new java.awt.Font("Bosch Sans Global", 1, 36)); // NOI18N
        jLabel2.setText("NOTA FISCAL - N°:");

        jLabel3.setFont(new java.awt.Font("Bosch Sans Global", 1, 36)); // NOI18N
        jLabel3.setText("TOTAL COM DESCONTO:");

        jLabel4.setFont(new java.awt.Font("Bosch Sans Global", 1, 36)); // NOI18N
        jLabel4.setText("TOTAL DA COMPRA:");

        jLabel5.setFont(new java.awt.Font("Bosch Sans Global", 1, 36)); // NOI18N
        jLabel5.setText("FORMA DE PAGAMENTO:");

        jLabel6.setFont(new java.awt.Font("Bosch Sans Global", 1, 36)); // NOI18N
        jLabel6.setText("DESCONTO:");

        jLabel7.setFont(new java.awt.Font("Bosch Sans Global", 1, 36)); // NOI18N
        jLabel7.setText("PAGAMENTO:");

        jLabel8.setFont(new java.awt.Font("Bosch Sans Global", 1, 36)); // NOI18N
        jLabel8.setText("TROCO:");

        jTNotaFiscal.setFont(new java.awt.Font("NSimSun", 0, 36)); // NOI18N
        jTNotaFiscal.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                jTNotaFiscalCaretUpdate(evt);
            }
        });

        jTDesconto.setFont(new java.awt.Font("NSimSun", 0, 36)); // NOI18N
        jTDesconto.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                jTDescontoCaretUpdate(evt);
            }
        });

        jTPagamento.setFont(new java.awt.Font("NSimSun", 0, 36)); // NOI18N
        jTPagamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTPagamentoActionPerformed(evt);
            }
        });

        jLSoma.setFont(new java.awt.Font("NSimSun", 0, 36)); // NOI18N

        jComboBoxFormaPagamento.setFont(new java.awt.Font("NSimSun", 0, 36)); // NOI18N
        jComboBoxFormaPagamento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Escolha", "Dinheiro", "Pix", "Débito", "Parcelado 3X" }));
        jComboBoxFormaPagamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxFormaPagamentoActionPerformed(evt);
            }
        });

        jLTotalDesconto.setFont(new java.awt.Font("NSimSun", 0, 36)); // NOI18N

        jLTroco.setFont(new java.awt.Font("NSimSun", 0, 36)); // NOI18N

        jLabel12.setFont(new java.awt.Font("NSimSun", 1, 36)); // NOI18N
        jLabel12.setText("%");

        jButton1.setFont(new java.awt.Font("Bosch Sans Global", 1, 18)); // NOI18N
        jButton1.setText("FINALIZAR VENDA");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(38, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel3)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8))
                        .addGap(39, 39, 39)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTPagamento)
                            .addComponent(jTDesconto)
                            .addComponent(jTNotaFiscal)
                            .addComponent(jLSoma, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jComboBoxFormaPagamento, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLTotalDesconto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLTroco, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel12)
                        .addGap(16, 16, 16))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(340, 340, 340))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(266, 266, 266))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1)
                .addGap(55, 55, 55)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(jTNotaFiscal, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLSoma, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel6))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jComboBoxFormaPagamento, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jTDesconto, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLTotalDesconto, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTPagamento, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLTroco, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTNotaFiscalCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_jTNotaFiscalCaretUpdate
        somaNF();
    }//GEN-LAST:event_jTNotaFiscalCaretUpdate

    private void jComboBoxFormaPagamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxFormaPagamentoActionPerformed
        escolhaPagamento();
    }//GEN-LAST:event_jComboBoxFormaPagamentoActionPerformed

    private void jTDescontoCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_jTDescontoCaretUpdate
        calcularDesconto();
    }//GEN-LAST:event_jTDescontoCaretUpdate

    private void jTPagamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTPagamentoActionPerformed
        troco();
    }//GEN-LAST:event_jTPagamentoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        caixa();
        limparCampos(jPanel1);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela_pagamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela_pagamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela_pagamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela_pagamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Tela_pagamento dialog = new Tela_pagamento(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    
    Banco_dados bd = new Banco_dados();
    
    private void idVenda(){
        if(bd.getConnection()){
            try{
                String query = "select max(id_vendas) as id_vendas from vendas";
                PreparedStatement smtp = bd.conexao.prepareStatement(query);
                ResultSet rs = smtp.executeQuery();
                while(rs.next()){
                    String add1 = rs.getString("id_vendas");
                    jTNotaFiscal.setText(add1);
                }
                smtp.close();
                bd.conexao.close();
            }catch(SQLException e){
                JOptionPane.showMessageDialog(null, "Erro: " + e.toString());
            }
        }
    }
    
    private void somaNF(){
        if(bd.getConnection()){
            try{
                String query = "select sum(total) as total from produto_has_vendas where fk_vendas = ?";
                PreparedStatement smtp = bd.conexao.prepareCall(query);
                smtp.setString(1, jTNotaFiscal.getText());
                ResultSet rs = smtp.executeQuery();
                if(rs.next()){
                    String add1 = rs.getString("total");
                    jLSoma.setText(add1);
                }
            }catch(SQLException erro){
                JOptionPane.showMessageDialog(null, "Erro de conexão: " + erro);
            }
        }
    }
    
    float valorTotal, desconto, valorFinal, troco, diferenca, descontoNovo;
    
    private void calcularDesconto(){
        valorTotal = Float.valueOf(jLSoma.getText());
        desconto = Float.valueOf(jTDesconto.getText());
        descontoNovo = (desconto/100);
        valorFinal = valorTotal - (valorTotal * descontoNovo);
        jLTotalDesconto.setText(String.valueOf(valorFinal));
    }
    
    private void troco(){
        String tipo = jComboBoxFormaPagamento.getSelectedItem().toString(); //registra a escolha
        if("Dinheiro".equals(tipo)){
            diferenca = Float.valueOf(jTPagamento.getText());
            troco = diferenca - valorFinal;
            jLTroco.setText(String.valueOf(troco));
        }else{
            jLTroco.setText("0");
        }
    }
    
    private void escolhaPagamento(){
        String tipo = jComboBoxFormaPagamento.getSelectedItem().toString(); //registra a escolha
        if("Dinheiro".equals(tipo)){
            jTDesconto.setText("10");
        }else{
            if("Pix".equals(tipo)){
                jTDesconto.setText("10");
            }else{
                if("Débito".equals(tipo)){
                    jTDesconto.setText("5");
                }else{
                    if("Parcelado 3X".equals(tipo)){
                        jTDesconto.setText("2");
                    }
                }
            }
        }
    }
    
    private void caixa(){
        if(bd.getConnection()){
            try{
                String query = "insert caixa (fk_vendas, valor_total, desconto, valor_final, forma_pagamento) values (?, ?, ?, ?, ?)";
                PreparedStatement smtp = bd.conexao.prepareStatement(query);
                smtp.setString(1, jTNotaFiscal.getText());
                smtp.setString(2, jLSoma.getText());
                smtp.setString(3, jTDesconto.getText());
                smtp.setString(4, jLTotalDesconto.getText());
                smtp.setString(5, jComboBoxFormaPagamento.getSelectedItem().toString());
                smtp.executeUpdate();
                smtp.close();
                bd.conexao.close();
            }catch(SQLException erro){
                JOptionPane.showMessageDialog(null, "Erro de gravação no banco: " + erro.toString());
            }
        }
    }

    private static void limparCampos(JPanel jPanel){
        Component[] componentes = jPanel.getComponents();
        for(Component componente : componentes){
            if(componente instanceof JTextField){
                JTextField camposTF = (JTextField)componente;
                camposTF.setText("");
            }
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBoxFormaPagamento;
    private javax.swing.JLabel jLSoma;
    private javax.swing.JLabel jLTotalDesconto;
    private javax.swing.JLabel jLTroco;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTDesconto;
    private javax.swing.JTextField jTNotaFiscal;
    private javax.swing.JTextField jTPagamento;
    // End of variables declaration//GEN-END:variables
}
